#!/usr/bin/env python3
"""
Railway Token Auto-Setup Script
================================

This script configures QX_TOKEN in Railway Variables automatically via the
Railway Public API. After a one-time setup (providing your Railway API token
and project ID), you can run this script locally to push a fresh Quotex
token to Railway — no dashboard clicks needed.

SETUP (one-time):
-----------------
1. Get a Railway API token:
   - Go to https://railway.app/account/tokens
   - Click "New Token" → name it "qx-token-sync"
   - Copy the token (starts with "railway-token-...")

2. Find your Railway project + service IDs:
   - Run: python3 setup_railway_token.py --list
   - This lists all your projects and services with their IDs.

3. Set environment variables (or pass via flags):
   export RAILWAY_API_TOKEN="railway-token-..."
   export RAILWAY_PROJECT_ID="prj-..."
   export RAILWAY_SERVICE_ID="svc-..."
   export RAILWAY_ENVIRONMENT_ID="env-..."  (optional, defaults to first)

USAGE:
------
  # Push a new token to Railway Variables (auto-redeploys):
  python3 setup_railway_token.py set --token "quotex-token.eyJhbGc..."

  # Read the current QX_TOKEN value (if accessible):
  python3 setup_railway_token.py get

  # List all projects and services (for one-time setup):
  python3 setup_railway_token.py --list

  # Verify Railway Variables are reachable:
  python3 setup_railway_token.py verify

NOTE:
-----
- Quotex tokens expire ~24 hours. You must extract a fresh token from your
  browser's DevTools (see RAILWAY_TOKEN_SETUP.md) and run this script.
- There is NO way to fully automate token extraction because Cloudflare
  blocks headless login from Railway's datacenter IPs. The token MUST come
  from a real browser session.
- For semi-automatic refresh, see the browser-extension approach documented
  in RAILWAY_TOKEN_SETUP.md.

Author: Generated by Super Z (2026-07-25 audit)
"""
import argparse
import json
import os
import sys
import urllib.request
import urllib.error
from typing import Optional


RAILWAY_API_BASE = "https://backboard.railway.app/graphql"


def _gql_query(api_token: str, query: str, variables: dict = None) -> dict:
    """Execute a GraphQL query against the Railway API."""
    headers = {
        "Authorization": f"Bearer {api_token}",
        "Content-Type": "application/json",
    }
    payload = json.dumps({"query": query, "variables": variables or {}}).encode()
    req = urllib.request.Request(RAILWAY_API_BASE, data=payload, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
            if "errors" in data:
                raise RuntimeError(f"Railway API errors: {data['errors']}")
            return data.get("data", {})
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ""
        raise RuntimeError(f"Railway API HTTP {e.code}: {body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Railway API network error: {e}") from e


def cmd_list(args):
    """List all projects and services for the given API token."""
    api_token = args.api_token or os.environ.get("RAILWAY_API_TOKEN")
    if not api_token:
        print("❌ RAILWAY_API_TOKEN not set. Get one from "
              "https://railway.app/account/tokens")
        sys.exit(1)

    print("📋 Your Railway projects:\n")
    query = """
    query {
      projects { edges { node { id name } } }
    }
    """
    data = _gql_query(api_token, query)
    projects = data.get("projects", {}).get("edges", [])
    if not projects:
        print("  (no projects found)")
        return

    for p in projects:
        proj = p["node"]
        print(f"  📁 {proj['name']}")
        print(f"     Project ID: {proj['id']}")

        # List services in this project
        svc_query = """
        query($projectId: String!) {
          project(id: $projectId) {
            services { edges { node { id name } } }
            environments { edges { node { id name } } }
          }
        }
        """
        try:
            svc_data = _gql_query(api_token, svc_query, {"projectId": proj["id"]})
            services = svc_data.get("project", {}).get("services", {}).get("edges", [])
            envs = svc_data.get("project", {}).get("environments", {}).get("edges", [])
            for s in services:
                print(f"     📦 Service: {s['node']['name']}  (ID: {s['node']['id']})")
            for e in envs:
                print(f"     🌍 Environment: {e['node']['name']}  (ID: {e['node']['id']})")
        except Exception as e:
            print(f"     ⚠️  could not load services: {e}")
        print()


def cmd_set(args):
    """Push a new QX_TOKEN to Railway Variables."""
    api_token = args.api_token or os.environ.get("RAILWAY_API_TOKEN")
    project_id = args.project_id or os.environ.get("RAILWAY_PROJECT_ID")
    service_id = args.service_id or os.environ.get("RAILWAY_SERVICE_ID")
    environment_id = args.environment_id or os.environ.get("RAILWAY_ENVIRONMENT_ID")

    if not api_token:
        print("❌ RAILWAY_API_TOKEN not set. Get one from "
              "https://railway.app/account/tokens")
        sys.exit(1)
    if not project_id:
        print("❌ RAILWAY_PROJECT_ID not set. Run with --list to find it.")
        sys.exit(1)
    if not service_id:
        print("❌ RAILWAY_SERVICE_ID not set. Run with --list to find it.")
        sys.exit(1)

    token_value = args.token or os.environ.get("QX_TOKEN_VALUE")
    if not token_value:
        print("❌ No token provided. Use --token or set QX_TOKEN_VALUE env var.")
        sys.exit(1)
    if len(token_value) < 20:
        print(f"❌ Token too short ({len(token_value)} chars). "
              "Expected a Quotex ssid (typically 200+ chars).")
        sys.exit(1)

    # Upsert the variable via GraphQL mutation
    mutation = """
    mutation VariableUpsert($input: VariableUpsertInput!) {
      variableUpsert(input: $input)
    }
    """
    variables = {
        "input": {
            "projectId": project_id,
            "serviceId": service_id,
            "environmentId": environment_id,
            "name": "QX_TOKEN",
            "value": token_value,
        }
    }
    print(f"⏳ Pushing QX_TOKEN to Railway (project={project_id}, "
          f"service={service_id})...")
    try:
        _gql_query(api_token, mutation, variables)
        print("✅ QX_TOKEN set in Railway Variables.")
        print("🚀 Railway will auto-redeploy within ~30 seconds.")
        print(f"   Token preview: {token_value[:8]}...{token_value[-4:]}")
        print("\nNext steps:")
        print("  1. Wait ~2-3 minutes for the deploy to finish")
        print("  2. Visit https://your-app.up.railway.app/api/debug")
        print("  3. Verify: sim_mode:false, connected:true")
    except Exception as e:
        print(f"❌ Failed to set QX_TOKEN: {e}")
        sys.exit(1)


def cmd_get(args):
    """Read the current QX_TOKEN from Railway Variables (if accessible)."""
    api_token = args.api_token or os.environ.get("RAILWAY_API_TOKEN")
    project_id = args.project_id or os.environ.get("RAILWAY_PROJECT_ID")
    service_id = args.service_id or os.environ.get("RAILWAY_SERVICE_ID")
    environment_id = args.environment_id or os.environ.get("RAILWAY_ENVIRONMENT_ID")

    if not all([api_token, project_id, service_id]):
        print("❌ RAILWAY_API_TOKEN, RAILWAY_PROJECT_ID, and "
              "RAILWAY_SERVICE_ID must all be set.")
        sys.exit(1)

    query = """
    query Variables($projectId: String!, $serviceId: String!) {
      project(id: $projectId) {
        service(id: $serviceId) {
          variables {
            edges {
              node { name value environments }
            }
          }
        }
      }
    }
    """
    data = _gql_query(api_token, query, {"projectId": project_id, "serviceId": service_id})
    edges = (data.get("project", {}).get("service", {})
             .get("variables", {}).get("edges", []))
    for e in edges:
        node = e["node"]
        if node["name"] == "QX_TOKEN":
            value = node["value"]
            if value:
                preview = f"{value[:8]}...{value[-4:]}" if len(value) > 12 else value
            else:
                preview = "(empty)"
            print(f"QX_TOKEN = {preview}")
            return
    print("QX_TOKEN not found in Railway Variables.")


def cmd_verify(args):
    """Verify Railway Variables configuration is reachable."""
    api_token = args.api_token or os.environ.get("RAILWAY_API_TOKEN")
    if not api_token:
        print("❌ RAILWAY_API_TOKEN not set.")
        sys.exit(1)

    print("🔍 Verifying Railway API access...")
    query = "query { me { id email } }"
    try:
        data = _gql_query(api_token, query)
        me = data.get("me", {})
        print(f"✅ Authenticated as: {me.get('email', 'unknown')} "
              f"(ID: {me.get('id', 'unknown')})")
        print("✅ Railway API is reachable and token is valid.")
    except Exception as e:
        print(f"❌ Railway API verification failed: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Railway Token Auto-Setup Script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--api-token", help="Railway API token (or set RAILWAY_API_TOKEN)")
    parser.add_argument("--project-id", help="Railway project ID (or set RAILWAY_PROJECT_ID)")
    parser.add_argument("--service-id", help="Railway service ID (or set RAILWAY_SERVICE_ID)")
    parser.add_argument("--environment-id",
                        help="Railway environment ID (or set RAILWAY_ENVIRONMENT_ID)")
    parser.add_argument("--list", action="store_true",
                        help="List all projects and services, then exit")

    sub = parser.add_subparsers(dest="command")
    sub_set = sub.add_parser("set", help="Push a new QX_TOKEN to Railway")
    sub_set.add_argument("--token", help="The Quotex token value (or set QX_TOKEN_VALUE)")
    sub.add_parser("get", help="Read the current QX_TOKEN value")
    sub.add_parser("verify", help="Verify Railway API access")

    args = parser.parse_args()

    if args.list:
        cmd_list(args)
        return
    if args.command == "set":
        cmd_set(args)
    elif args.command == "get":
        cmd_get(args)
    elif args.command == "verify":
        cmd_verify(args)
    else:
        parser.print_help()
        print("\nFirst-time setup:")
        print("  1. Get Railway API token: https://railway.app/account/tokens")
        print("  2. List projects:  python3 setup_railway_token.py --list")
        print("  3. Set env vars:   export RAILWAY_API_TOKEN=... (etc)")
        print("  4. Push a token:   python3 setup_railway_token.py set --token '...'")


if __name__ == "__main__":
    main()
